name: telem-agent # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: MQTT proxy for authorization and package inspection # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

layout:
  /etc/.env:
    bind-file: $SNAP_COMMON/etc/.env

parts:
  telem-agent:
    plugin: go
    source-type: local
    source: .
    build-snaps: [go/latest/stable]

plugs:
  agent-control:
    interface: confdb
    account: 6mluykWFsbpSV8RGPGjH7KFAkAOvdRyN
    view: telem-agent/control-agent
    role: custodian

  topic-control:
    interface: confdb
    account: 6mluykWFsbpSV8RGPGjH7KFAkAOvdRyN
    view: telem-agent/control-topics
    role: custodian

  ssl:
    interface: home
    read: all

apps:
  telem-agent:
    command: bin/cmd --env /etc/.env
    daemon: simple
    plugs:
      - system-observe
      - ssl
      - network
      - network-bind
      - agent-control
      - snapd-control
      - topic-control
      - network-observe