# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

name: Vulnerability Check

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
jobs:
  vul-scan:
    name: Scan vulnerabilites
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
          cache-dependency-path: "go.sum"
      
      - name: Install secscan snap
        run: |
            sudo snap install canonical-secscan-client
            sudo snap connect canonical-secscan-client:home system:home

      - name: archive the repository
        run: |
            mkdir ${{github.workspace}}/archive
            tar -zcf ${{github.workspace}}/archive/telem_agent.tar.gz --exclude=${{github.workspace}}/archive ${{ github.workspace }}  

      - name: Install Open VPN
        run: sudo apt-get update && sudo apt-get install -y openvpn

      - name: Connect VPN
        uses: golfzaptw/action-connect-ovpn@master
        id: connect_vpn
        env:
          CA_CRT: ${{ secrets.CA_CRT}}
          USER_CRT: ${{ secrets.USER_CRT }}
          USER_KEY: ${{ secrets.USER_KEY }}


      - name: Run Black Duck Vulnerability scan
        run: |
           secscan-client submit --scanner blackduck --type package --format archive \
           ${{github.workspace}}/telem_agent.tar.gz  --wait-and-print 

    #   - name: Install dependencies
    #     run: |
    #       go install github.com/axw/gocov/gocov@latest
    #       go install github.com/AlekSi/gocov-xml@latest
    #       go install honnef.co/go/tools/cmd/staticcheck@latest


    #   - name: Build Binaries
    #     run: |
    #       make all
